apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: rstccp5xk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rstccp5xk-nodejs 
  name: rstccp5xk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: rstccp5xk-nodejs 
